title: UnitVectorY Labs Guide
description: "Useful information and Guides from UnitVectorY Labs"

remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-remote-theme

color_scheme: dark

#logo: "/assets/logo_transparent.png"

baseurl: /uvy-labs-guide

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.8.0"

just_the_docs:
  collections:
    bestpractices:
      name: Best Practices
      nav_fold: false
    javadevelopment:
      name: Java Development
      nav_fold: false
        
# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/uvy-labs-guide"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
